### ISSUE TITLE
events?

### ISSUE THREAD

**Issue by macMikey** [TihounaNasrallah/qodly-calendar#22]
is there a thought about adding events to the component, so we can do things like selecting a date? That would be useful in a dialog to act as a date picker, or drilling into the events on a date.

**Comment by TihounaNasrallah** [comment]
Hello Mikey, thank you for your feedback.
Yes, i'm currently working on integrating events to the component (onSelect, ...), and i will update it soon.
As for the date picker, there is a component for that, you can check it out [here](https://github.com/rihab-ze/qodly_datePicker).

**Comment by macMikey** [comment]
yes, i know there is a date picker. the reason for doing it on a calendar was so that the user can see a schedule and then drill into a date, from there.

**Comment by TihounaNasrallah** [comment]
Hello Mikey, i just updated the version of qodly-calender (`v0.2.0`), now you can set events (open modal, change a datasource, ...) when a date is selected (OnSelect). You only need to create a `date` type datasource, and pass it as the `selected date` property.
